### ISSUE TITLE
Scanner

### ISSUE THREAD

**Issue by weicai812** [zhamri/STIA1123-Programming2#1]
When we use Scanner to input our data，why String z cannot be input？and when I input data x same with the if statement，the result shows x！=java？
```
import java.util.Scanner;
public class CompareString2 {
    public static void main(String[] args) {
    Scanner sc= new Scanner(System.in);
    String x;
    int y;
    String z;
    
      System.out.println("input x");
      x=sc.nextLine();
      System.out.println(x);
    
      System.out.println("input y");
      y=sc.nextInt();
      System.out.println(y);
    
      System.out.println("input z");
      z=sc.nextLine();
      System.out.println(z);
      
      if (x=="Java") {
            System.out.println("x = Java");
         }
         else {
            System.out.println("x != Java");
         }
    
    }
}
```

**Comment by zhamri** [comment]
> When we use Scanner to input our data，why String z cannot be input？and when I input data x same with the if statement，the result shows x！=java？
> 
> ```
> import java.util.Scanner;
> public class CompareString2 {
>     public static void main(String[] args) {
>     Scanner sc= new Scanner(System.in);
>     String x;
>     int y;
>     String z;
>     
>       System.out.println("input x");
>       x=sc.nextLine();
>       System.out.println(x);
>     
>       System.out.println("input y");
>       y=sc.nextInt();
>       System.out.println(y);
>     
>       System.out.println("input z");
>       z=sc.nextLine();
>       System.out.println(z);
>       
>       if (x=="Java") {
>             System.out.println("x = Java");
>          }
>          else {
>             System.out.println("x != Java");
>          }
>     
>     }
> }
> ```

https://www.geeksforgeeks.org/why-is-scanner-skipping-nextline-after-use-of-other-next-functions/

**Comment by zhamri** [comment]
See the example below:

* https://github.com/zhamri/STIA1123-Programming2/blob/master/src/main/java/my/zhamri/stia1123/string/ExampleScanner1.java
* https://github.com/zhamri/STIA1123-Programming2/blob/master/src/main/java/my/zhamri/stia1123/string/CompareString3.java
